apiVersion: v1
kind: Namespace
metadata:
  name: delivery-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: delivery-service
  labels:
    app: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: mash02/delivery-service:latest
          ports:
            - containerPort: 50053
          envFrom:
            - secretRef:
                name: delivery-service-secret
          env:
            - name: REDIS_HOST
              value: redis #  namespace
            - name: REDIS_PORT
              value: '6379'
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: delivery-service
spec:
  selector:
    app: delivery-service
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053
  type: ClusterIP
