# ---------- development stage ---------------
FROM node:alpine AS development

WORKDIR usr/src/app

# Installion of dev dependencies
COPY package.json ./

COPY package-lock.yaml ./

RUN npm install -g npm
RUN npm install -g @nestjs/cli

RUN npm install

COPY . .

# Do the production build inside the base image
RUN npm run build

# ---------- production stage ---------------

FROM node:alpine AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR usr/src/app

COPY package.json ./

COPY package-lock.yaml ./

RUN npm install -g npm
RUN npm install -g @nestjs/cli

RUN npm install --prod

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/apps/reservations/main"]